spring.application.name=order-service


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable feign client logs (optional)
logging.level.org.springframework.cloud.openfeign=DEBUG
